name: Docker Image & Deploy CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Vue Build
      run: |
        npm install --prefix front_end
        npm run --prefix front_end build
    - name: Front End Resources Copy
      run: |
        mkdir app/static
        mv front_end/dist/* app/static/
    - name: Get Version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF:11}" >> "$GITHUB_ENV"
        echo $RELEASE_VERSION
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lee0609x/piapia:${{ GITHUB_ENV.RELEASE_VERSION }}
    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Image
      run: docker push lee0609x/piapia:$RELEASE_VERSION
    - name: SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CLOUD_HOST }}
        username: ${{ secrets.CLOUD_USERNAME }}
        password: ${{ secrets.CLOUD_PASSWORD }}
        port: 22
        script: |
          docker pull lee0609x/piapia:$RELEASE_VERSION
          docker stop piapia
          docker rm `docker ps -a | grep Exited | grep piapia | awk '{print $1}'`
          docker rmi `docker images | grep none | grep "lee0609x/piapia" | awk '{print $3}'`
          docker run --name piapia -p 80:80 -d lee0609x/piapia:$RELEASE_VERSION